# Generated by Django 3.2.25 on 2024-09-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ball_dx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ball_dy',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ball_x',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ball_y',
        ),
        migrations.RemoveField(
            model_name='game',
            name='paddle1_y',
        ),
        migrations.RemoveField(
            model_name='game',
            name='paddle2_y',
        ),
    ]
